### ISSUE TITLE
add scipy to Dockerfile

### ISSUE THREAD

**Issue by pocin** [keboola/docker-custom-python#3]
Would it be possible to pip install `scipy` and `scikit-learn` in the Dockerfile? 

I think it wouldn't inflate the size much and it takes ages if one wants to install them in a transformation or a custom science python app at runtime.

**Comment by odinuv** [comment]
definitely, scipy should be pre-installed https://github.com/keboola/docker-custom-python/commit/d3052f3d402f5741640d8841a3e3a32978d0e8fb and it's an error it isn't there

**Comment by pocin** [comment]
Yeah, I see the problem now;
```

$ docker run --rm -i -t quay.io/keboola/docker-custom-python:1.4.0 bash
root@4660dc06b30a:/home# python3
Python 3.6.2 (default, Jul 24 2017, 19:47:39)
[GCC 4.9.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import scipy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'scipy'
>>>
root@4660dc06b30a:/home# python2
Python 2.7.9 (default, Jun 29 2016, 13:08:31)
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import scipy
>>>
root@4660dc06b30a:/home# which python2
/usr/bin/python2
root@4660dc06b30a:/home# which python3
/usr/local/bin/python3
root@4660dc06b30a:/home#

```

The `apt install` installs them for the system python2 interpreter (is that even necessary?) and so adding them to the `pip` should fix things.

**Comment by odinuv** [comment]
it used to be necessary back then, not anymore

**Comment by odinuv** [comment]
fixed in https://github.com/keboola/docker-custom-python/commit/fbda9b4ccfdf96feb8cec83d54cc75bd2e1c9c24 and in https://github.com/keboola/python-transformation/commit/fa96cd67c96d8a95ab7722a2d9b91cb2ed98cd4b

**Comment by pocin** [comment]
Thanks for that 🍺 . Can we also add `scikit-learn`? It can easily wait untill next update :)

**Comment by odinuv** [comment]
omg, that was a mistake, fixed again in https://github.com/keboola/docker-custom-python/commit/df0a708af8612312de4cf030246d2401808b5d7e and https://github.com/keboola/python-transformation/commit/5d99b1152cbd933f99a7ecf40dbd630c75679cc9 🙄
